---
title: "Lab #3: Monty Hall Problem Simulation"
author: "Ceyda Durmaz"
date: "11/09/2020"
output:
  prettydoc::html_pretty:
    theme: leonids
    highlight: github
editor_options: 
  chunk_output_type: console
---

Link to GitHub Repository: https://github.com/cdurmaz569/Data_Science_I_Lab/tree/master/Lab_3

# Load library and set seed
```{r warning=FALSE, message=FALSE}
# load libraries 
library(dplyr)

# set seed
set.seed(18)
```

# Functions 
```{r warning=FALSE, message=FALSE}
#' Monty Hall Simulation 
#'
#' Run Monty Hall Simulation 
#' 
#' @param switch boolean for using switch strategy; TRUE = use, FALSE = do not
#'
#' @return booleawn indicating game result; TRUE = win, FALSE = loss
run_monty <- function(switch = TRUE){
  
  # create all doors
  doors <- paste0("door_", 1:3)
  
  # assign door to contestant's first pick
  door_pick_1 <- sample(doors, 1)
  
  # assign door to prize 
  door_prize <- sample(doors, 1)
  
  # assign door to host
  door_host <- setdiff(doors, c(door_prize, door_pick_1)) %>% sample(1)
  
  # if switch == TRUE, contestent will switch to 
  if(switch){
    door_pick_final = setdiff(doors, c(door_pick_1, door_host))
  } else{
    door_pick_final = door_pick_1
  }
  
  # return whether contestant picked door with prize 
  ifelse(door_pick_final == door_prize, TRUE, FALSE)
  
}

#' Run Simulation Multiple Times
#'
#' Run Monty Hall simulation multiple times 
#' 
#' @param n int for number of times to run simulation 
#' @param switch boolean for using switch strategy 
#'
#' @return table of proportions of win (TRUE) and loss (FALSE)
multi_monty <- function(n = 1000, switch = TRUE){
  
  replicate(n, run_monty(switch)) %>% 
    table() %>%
    prop.table()
  
}

```

# Run Monty Hall Problem Simulation
```{r warning=FALSE, message=FALSE}
# run simulation for 1000 plays with switching strategy
multi_monty()

# run simulation for 1000 plays without switching strategy 
multi_monty(switch = FALSE)
```

